machine:
  php:
    version: 7.0.4
  services:
    - mysql
  environment:
    DEBUG: true
    DATABASE_URL: "mysql://ubuntu:@localhost/hoge_develop?unix_socket=/var/run/mysqld/mysqld.sock&encoding=utf8mb4&timezone=UTC&cacheMetadata=true"
    DATABASE_TEST_URL: "mysql://ubuntu:@localhost/hoge_test?unix_socket=/var/run/mysqld/mysqld.sock&encoding=utf8mb4&timezone=UTC&cacheMetadata=true"
dependencies:
  cache_directories:
    - ~/.composer/cache
  override:
    - composer install --dev --no-interaction
  post:
    - chmod 777 ./bin/cake
    - mysql -u ubuntu -e "CREATE DATABASE hoge_develop CHARSET utf8mb4;"
    - mysql -u ubuntu -e "CREATE DATABASE hoge_test CHARSET utf8mb4;"
    - ./bin/cake migrations migrate
test:
  override:
    - mkdir -p $CIRCLE_TEST_REPORTS/phpunit
    - vendor/bin/phpunit --configuration phpunit.xml.dist --log-junit junit.xml